WHITESPACE = _{ " " | "\t" | NEWLINE }

Backslash = _{ "\\" }
OpenBrace = _{ "{" }
CloseBrace = _{ "}" }
OpenBracket = _{ "[" }
CloseBracket = _{ "]" }
DoubleQuote = _{ "\"" }

AsciiChar = _{ ASCII_ALPHANUMERIC }
Literal = { AsciiChar+ }

AttributeKey = { AsciiChar+ }
AttributeValue = { (!DoubleQuote ~ ANY)* }
Attribute = ${ AttributeKey ~ "=" ~ DoubleQuote ~ AttributeValue ~ DoubleQuote }
AttributeList = { OpenBracket ~ Attribute+ ~ CloseBracket }

ElementName = { AsciiChar+ }
ElementContent = _{ (Literal | Element)+ }
Element = {
  Backslash ~
  ElementName ~
  AttributeList? ~
  OpenBrace ~
  ElementContent ~
  CloseBrace
}

File = { SOI ~ Element+ ~ EOI }